### ISSUE TITLE
Патчи не нужны

### ISSUE THREAD

**Issue by mkpankov** [kgv/rust_book_ru#120]
Насколько я понимаю, содержимое директории `patch` - созданные в какой-то момент пачти относительно оригинала. Получается, что если оригинал был изменён с момента создания патча, он не наложится.

В целом, я так понимаю, они особо не нужны - мы можем просто скопировать файлы на место оригинальных файлов, и это будет правильно.

Предлагаю удалить.

**Comment by kgv** [comment]
Патчи были добавлены для конвертации из измененного формата, используемого для русского языка в формат оригинала. Если я правлильно понял Стива, в rusbook будет добавлена фича многоязычности подобная [этой](https://github.com/GitbookIO/gitbook#user-content-multi-languages), и для того чтобы получить набор файлов с русским переводом, формат которых полностью совпадает с оригиналом, и были созданы патси. По скольку многоязычность была добавлена в виде ссылки на репозиторий с русским переводом, то смысла в них тоже особого не вижу, будем придерживаться своего формата.
:+1:  если коротко ))
