### ISSUE TITLE
Pdf/Mobi/Epub версии книги

### ISSUE THREAD

**Issue by funkill** [kgv/rust_book_ru#126]
Сконвертированные версии книги (книга не далеко не последней версии).
Все файлы сконвертированы при помощи colibre (используется gitbook'ом). 
Хорошее оглавление сделать не получилось (у colibre ограничение в 50 глав, чтоб делать иерархию глав, надо добавлять соответствующие стили к заголовкам глав. Чтобы их добавить, надо изменять rustdoc).
Что лучше изменить в оформлении, что можно оставить?
Pdf версию подгонял под оформление, которое используется в gh-pages, Mobi и Epub похоже не полностью подхватили оформление.

[Pdf](https://github.com/funkill/rust_book_ru/raw/gh-pages-test/index.pdf)
[Epub](https://github.com/funkill/rust_book_ru/raw/gh-pages-test/rustbook.epub)
[Mobi](https://github.com/funkill/rust_book_ru/raw/gh-pages-test/rustbook.mobi)

**Comment by mkpankov** [comment]
:+1: постараюсь посмотреть в ближайшее время

**Comment by jiumx60rus** [comment]
Глянул pdf
Выглядит очень годно
Багов с md и т.п. не нашёл
Только можно убрать жёлтый цвет выделения ссылок(внутри книги)
Up
Остальное криво отображается
Шрифт большой слишком и не подсветки + не нормального форматирования текста(весь код поехал)

**Comment by funkill** [comment]
Скорее всего жёлтым цветом ссылки просмотрщик выделяет. У меня в qpdfviewer ссылки обведены в рамку, в mupdf - без какого-либо стороннего оформления (просто синеватый цвет шрифта и подчёркивание). В moonreader - к подчёркиванию и шрифту, как в mupdf, добавился такого же цвета полупрозрачный фон.

**Comment by jiumx60rus** [comment]
А точно...просто в двух просмоторщиках у меня совпало выделение.

**Comment by mkpankov** [comment]
Несколько предложений:
- Сделать шрифт покрупнее
- Сделать полуторный междустрочный интервал
- Сделать выравнивание по ширине

В целом, вроде, хорошо всё

**Comment by mkpankov** [comment]
Предлагаю ещё убрать подчёркивание заголовков

**Comment by jiumx60rus** [comment]
Со шрифтом согласен

**Comment by funkill** [comment]
Ссылки обновлены.
Шриф сделал 16px (был 12px), выравнивание по ширине добавил. Межстрочный интервал был примерно 1.49 (плюс отступы между абзацами). Отсупы убрал (чтоб везде был 1.5), сам интервал увеличил до 1.5.
Стоит ли делать красную строку к абзацам (сейчас, на мой взгляд, сложнее воспринимать текст)? Если стоит, то делать ли такой же отступ для блоков с кодом? Или сделать побольше отступ между абзацами?

**Comment by mkpankov** [comment]
@funkill круто :+1: 

Да, мне тоже красной строки не хватает. Для блоков с кодом я думаю, не надо. Между абзацами отступ давай немного увеличим.

Кстати, есть возможность запретить разбивать блоки с кодом при переносе? Например, на пятой странице осталась одна фигурная скобка от предыдущего блока.

**Comment by funkill** [comment]
Добавил красную строку (40px). Отступ такой же ширины сделал для списков. 
Между абзацами добавлен отступ в 10px. 
Запрещена разбивка блоков с кодом.
Убраны ссылки на предыдущую/следующую главы в конце каждой главы.

[PDF](https://github.com/funkill/rust_book_ru/raw/c73362d580b558e167269072bc1f912de05a770f/index.pdf)
[EPUB](https://github.com/funkill/rust_book_ru/raw/c73362d580b558e167269072bc1f912de05a770f/rustbook.epub)
[MOBI](https://github.com/funkill/rust_book_ru/raw/c73362d580b558e167269072bc1f912de05a770f/rustbook.mobi)

**Comment by mkpankov** [comment]
@funkill классно, мне нравится как сейчас PDF выглядит.

Добавишь в сборку на Travis?

**Comment by funkill** [comment]
Оставить только pdf или остальные тоже?
И такой вопрос: куда сконвертированные файлы складывать? Для тестирования я пока что в ту же ветку складывал, в которой собирал книгу.

**Comment by mkpankov** [comment]
Думаю, все.

Ты имеешь ввиду что клал в `gh-pages`? Если оттуда можно скачивать, то почему нет.

**Comment by jiumx60rus** [comment]
Проверил все норм отображается.
Выглядит отлично(цвета, форматирование и т.п.)

**Comment by espdev** [comment]
Попробовал открыть Epub-файл на устройстве NOOK. Корректно отображается только первая страница, затем весь текст книги отображается в один столбец слева экрана (столбик текста шириной в одну букву сверху-вниз). При попытке перейти на какую-либо страницу через навигатор вылетает в библиотеку.

**Comment by mkpankov** [comment]
@espdev Спасибо за отчёт!

Я переношу его в отдельную новую задачу, потому что эта задача не о том, и она закрыта.
