### ISSUE TITLE
Что стоит переводить, а что нет. Обсуждение.

### ISSUE THREAD

**Issue by mkpankov** [kgv/rust_book_ru#13]
Как насчёт перевода строк, используемых в коде примеров?

Пример: 

``` rust
let a = [1, 2, 3];

println!("a has {} elements", a.len());
for e in a.iter() {
    println!("{}", e);
}
```

можно было бы перевести как 

``` rust
let a = [1, 2, 3];

println!("Число элементов в a: {}", a.len());
for e in a.iter() {
    println!("{}", e);
}
```

По-моему это было бы более приятно русскоязычному читателю и подчеркнет работу с Юникодом из коробки без каких-либо проблем.

Как вы считаете?

**Comment by ithamsteri** [comment]
Я согласен. :+1:
Так как читателю понятнее будет.

**Comment by mkpankov** [comment]
Один тонкий момент: не стоит переводить имена вроде Graydon и Niko как Григорий и Николай --- это отсылка к создателям языка :)

**Comment by mkpankov** [comment]
Ещё надо не увлекаться и не переводить сообщения об ошибках компилятора.

**Comment by kgv** [comment]
> Ещё надо не увлекаться и не переводить сообщения об ошибках компилятора.

:+1:

**Comment by kgv** [comment]
Из этой же области вопрос: цитаты лучше переводить или оставлять на языке оригинала?
Причем я встречал цитаты двух типов:
- Декоративного характера.  [пример](https://github.com/kgv/rust_book_ru/blob/master/error-handling.md)
- Несут в себе некий смысл, на который опирается дальнейшее повествование. [пример](https://github.com/kgv/rust_book_ru/blob/master/concurrency.md#%D0%91%D0%B5%D0%B7%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%BE%D0%B5-%D1%81%D0%BE%D0%B2%D0%BC%D0%B5%D1%81%D1%82%D0%BD%D0%BE%D0%B5-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D1%8F%D0%B5%D0%BC%D0%BE%D0%B3%D0%BE-%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F)

**Comment by mkpankov** [comment]
Я думаю, что декоративные цитаты можно заменять аналогичными по смыслу русскоязычными при их наличии. Мне кажется, в большинстве случаев таких цитат на русском не найдёшь :)

А "смысловые" наверное надо переводить близко к тексту.

**Comment by kgv** [comment]
Также хочу заметить что в док-комментариях к коду Rust могут присутствовать markdown заголовки, например:

> # Examples

В [разделе о документации](https://github.com/rust-lang/rust/blob/master/src/doc/trpl/documentation.md#special-sections) сказано, что они не являются частью синтаксиса, но являются соглашением.
Думаю их переводить не следует.

**Comment by kgv** [comment]
Добавил [правила перевода](https://github.com/kgv/rust_book_ru/blob/master/RULES.md)
