### ISSUE TITLE
В web-версии rustbook сломано оглавление

### ISSUE THREAD

**Issue by mkpankov** [kgv/rust_book_ru#132]
http://kgv.github.io/rust_book_ru/

Слева нажимаем на "Установка Rust", попадаем на http://kgv.github.io/src/installing-rust.html (404).

Правильный URL - http://kgv.github.io/rust_book_ru/src/installing-rust.html

**Comment by funkill** [comment]
Похоже новый rustbook как-то коряво обработал ссылки и посчитал, что README.html лежит вместе с остальными.

**Comment by mkpankov** [comment]
Да, я что-то такое тоже замечал - он как будто от текущей директории отталкивается.

**Comment by funkill** [comment]
Предлагаю пока что откатить rustbook до предыдущей версии (eb96cc8)

**Comment by mkpankov** [comment]
Согласен

**Comment by mkpankov** [comment]
А зачем rustbook обновлять?

**Comment by mkpankov** [comment]
Ок, сиюминутную проблему откат решил, но причина поломки не ясна. Как, впрочем, и цель обновления :)
