### ISSUE TITLE
Ссылки на Rust документацию

### ISSUE THREAD

**Issue by kgv** [kgv/rust_book_ru#141]
Я тут хотел подчистить все ссылки на документацию, которые на данный момент пока не изменены и имеют вид `../std/*.html`.
И подумал, почему бы в тревисе не изменять все ссылки перед конвертацией, навскидку `sed -i "s%\.\./\(std/.*\.html\)%http://doc.rust-lang.org/\1%g" src/*.md`. Это мне кажется удобнее будет.

**Comment by mkpankov** [comment]
Я думаю, что Трэвису я бы всё-таки это не доверял - вдруг регулярка что-то неожиданное сопоставит.

Предлагаю самому sed прогнать просто и закоммитить.
