### ISSUE TITLE
Перевод "Rustaceans"

### ISSUE THREAD

**Issue by mkpankov** [kgv/rust_book_ru#176]
Текущие варианты:
- растаманы
- растишки
- растониане
- растообразные

Текущее обсуждение (из чата и ревью):

> kgv: Кстати, "Rustaceans" насколько я понял это игра слов и на русский должна переводиться как Растообразные. В ру комьюнити вроде как прижилось "Растаманы". Еще мне очень понравилась версия "Растишки" XD.
> Как-то будем это отражать?
> mkpankov: @kgv насчёт растаманов - мне наркоманская коннотация не нравится, думаю лучше что-то более нейтральное
> с другой стороны, растообразные - это слишком похоже на ракообразные. так и задумано в оригинале, но у нас "рак" опять-таки имеет негативный оттенок и смысл "человек, у которого руки из жопы" 
> не знаю в общем, сложно всё как-то 
> kgv 6 minutes ago  
> @mkpankov у меня похожее отношение к этим двум переводам... оставить не переведенным чтоль... 
> mkpankov 5 minutes ago  
> ржавник может какой-нибудь, без понятия
> надо мозговой штурм устроить, хех
> kgv a minute ago
> Я в вначале думал Rustaceans - это игра слов типа Растониане (вроде как Мрсиане с другой планеты), мне нравилассь такая концепция, но потом понял что это всего-лишь Растообразные )))
> mkpankov a few seconds ago  
> растониане кстати лучше

**Comment by kgv** [comment]
[Голосование](http://strawpoll.me/4644480)

**Comment by mkpankov** [comment]
@kgv ну бросьте, какое голосование. Голосование, по-моему - это "нам лень думать, бросим кости общественного мнения".

**Comment by kgv** [comment]
@mkpankov Перевод этого прозвища - чисто дело вкуса. Голосование - это статистика. По-моему - голосование - это то, как само Ру Rust комьюнити предпочитает себя называть.

**Comment by petrochenkov** [comment]
Всё плохо.
Мне кажется, стоит один раз объяснить игру слов, а потом использовать что-нибудь нейтральное вроде "программисты на Rust" или "пользователи Rust", тем более что встречается всего несколько раз. На русском даже для старых языков такие названия не приживаются кроме как в _очень_ неформальном контексте (плюсовики, пыхеры, ~~жаба-макаки~~), т.е. в книгах/документации такого не встретишь.

**Comment by mkpankov** [comment]
@petrochenkov стоит отметить, что книга в оригинале и написана в неформальном стиле, и прозвище изначально подаётся как шуточное. Раз-другой упомянуть его и в переводе, по-моему, можно, если подходящий перевод найдётся.

Приведённые вами примеры родились сразу на русском - в сленговом английском нет названия "plusers". И "rustacean" образовано иначе, нежели какой-нибудь "haskeller".

**Comment by mkpankov** [comment]
Много думал.

Пришёл к выводу, что по-настоящему пользоваться переводом этого прозвища в книге нельзя. Вот почему.

В оригинале Rustaceans - придуманное первоначальными авторами прозвище _для самих себя_. Пытаясь как-то его перевести, мы пытаемся формализовать и пропихнуть в русское сообщество _шутку_. Это глупо, не донесёт никакой шутливости, и вообще воспринимается как попытка дать людям прозвище.

Имея в виду всё это, я считаю, что надо где-то привести _каноничный_ перевод прозвища - т.е. _растообразные_ - и объяснить игру слов. Это просто чтобы народ понимал откуда что взялось. Самих программистов действительно лучше называть "программистами на Rust" или "пользователями Rust", как посоветовал @petrochenkov.

Что касается русскоязычного аналога - его пока нет и быть не должно. Если он появится в результате общения внутри русскоязычного сообщества, причём такой, что имённо один вариант лучше всего приживётся, то можно будет включить его в будущие версии книги. Т.е. сообщество должно само себя обозвать - тогда будет нормально.

А пока не надо.

**Comment by suhr** [comment]
Здесь соглашусь. Это не художественная литература, где шутки необходимо переводить.

**Comment by heaviss** [comment]
Могу предложить вариант "Rustафарианцы"/"Rustафариане"  в значении "приверженцы идеологии Rust". На мой взгляд наркоманских ноток меньше, чем в "растаманы", и намного благозвучнее остальных трёх вариантов.
Или "Rustияне"/ "Rustиане"/ "Rustианцы" как созвучные россиянам, марсианам и американцам

Отмечу также, что согласен с вышесказанным - не стоит вставлять такой перевод где попало, достаточно один раз объяснить игру слов. Однако считаю, что перевести как-нибудь это нужно, пусть это будет маленькая привилегия переводчиков - предложить "прозвище" программистам на Rust в книге про Rust. Ведь вы тоже сообщество, значит, имеете право вносить варианты.

**Comment by suhr** [comment]
> предложить "прозвище" программистам на Rust в книге про Rust

Пусть лучше сообщество сформирует своё прозвище.

**Comment by mkpankov** [comment]
Согласен, объявление убрал, закрываю

**Comment by Truenya** [comment]
Да хэдкрабы же, очевидно.
Олды поймут, ньфаги запомнят.
