### ISSUE TITLE
Лицо автора

### ISSUE THREAD

**Issue by mkpankov** [kgv/rust_book_ru#180]
В некоторых местах автор пишет про себя "я": "вот, про что я говорил", и т.д. Но не везде - также, часто встечается "мы".

При этом много где про какие-то описываемые вещи говорится "наш/наши": "наш стек", "наши структуры" и т.д.

В связи с этим, и поскольку у перевода по сути много авторов, предлагаю изменить лицо на "мы" и писать в немного формальном стиле научных статей: "мы пишем", "мы получаем", и т.д.

**Comment by kgv** [comment]
:+1:

**Comment by kgv** [comment]
[Добавил в правила](https://github.com/kgv/rust_book_ru/wiki/%D0%9F%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0#%D0%9F%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0-%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4%D0%B0)
