### ISSUE TITLE
Перевод "native"

### ISSUE THREAD

**Issue by mkpankov** [kgv/rust_book_ru#189]
Например, в нескольких местах есть "native libraries". "Родные библиотеки" звучит странно.

Есть что-то устоявшееся?

**Comment by kgv** [comment]
Я всегда "нативные библиотеки" употреблял...

**Comment by mkpankov** [comment]
@kgv ну да, за неимением лучшего...

Я имею ввиду, может всё же "более нормативное" есть/можно придумать.

**Comment by jiumx60rus** [comment]
Нативная в скобках родная
Или в книге по clojure писали "родная (native)"
