### ISSUE TITLE
Перевод "unsafe"

### ISSUE THREAD

**Issue by mkpankov** [kgv/rust_book_ru#190]
Нужно переводить не как "небезопасный", а как "опасный". Двойное отрицание затрудняет понимание, да и слово длиннее почти в два раза.

Применимо к "unsafe block", "unsafe function", "unsafe pointer", "unsafe operation" и т.д.

**Comment by kgv** [comment]
Не согласен. Для меня два антонима опасный/безопасный звучат как равноценные. С другой стороны, небезопасный/безопасный звучат как неравноценные. То есть небезопасный - это нерегулярная, исключительная, нечасто случающаяся ситуация (как и должно быть). Поэтому, на мой взгляд, эти термины (небезопасный/безопасный) больше подходят в данном контексте.

**Comment by jiumx60rus** [comment]
@kgv Согласен
Многие его так и переводят
Пример https://msdn.microsoft.com/ru-ru/library/chfa2zb8.aspx
