### ISSUE TITLE
Ширина строк

### ISSUE THREAD

**Issue by kgv** [kgv/rust_book_ru#20]
Оригинальная ширина текста - 80. При чистовом форматировании предлагаю делать ширину такой же.
PS: На некоторых редакторах у меня нужно было задавать 81. Так что перед форматированием лучше параметры для своего редактора на оригинале, чтобы не было лишних переносов.

**Comment by mkpankov** [comment]
Не понял в P.S. про "на оригинале".

**Comment by kgv** [comment]
> Не понял в P.S. про "на оригинале".

Я имел ввиду, что если для оригинального файла (не переведенного) при выставлении заданной ширины (80) переноса происходит нарушение целостности, то значит при форматировании следует указать 81. Я это написал только потому что столкнулся с таким в одном из редакторов.
@mkpankov у ваших отредактированных файлов было все ок с шириной. И они пока единственные отредактированные по ширине.

**Comment by mkpankov** [comment]
А, да, согласен :+1:

**Comment by kgv** [comment]
Добавил [правила перевода](https://github.com/kgv/rust_book_ru/blob/master/RULES.md)
