### ISSUE TITLE
Стек и куча

### ISSUE THREAD

**Issue by mxseev** [kgv/rust_book_ru#201]
Это число равно 2<sup>30</sup>
![screenshot from 2015-06-27 22-03-35](https://cloud.githubusercontent.com/assets/10381174/8393071/5d4437ec-1d18-11e5-8fd2-1255c321d6a6.png)

**Comment by mkpankov** [comment]
@Ralvke спасибо за сообщение!

@funkill это же по идее rustbook должен обрабатывать, т.к. это встроенный html?

**Comment by suhr** [comment]
> 1,073,741,824

В русском языке разряды отделяют пробелами: «1 073 741 824».

**Comment by mkpankov** [comment]
@suhr да, но сообщение не об этом. Давай сосредоточимся на решении конкретной проблемы. 

Создай, пожалуйста, отдельную задачу на исправление разделителей.
