### ISSUE TITLE
Битые ссылки на kgv.github.io

### ISSUE THREAD

**Issue by jiumx60rus** [kgv/rust_book_ru#204]
---
- [x] http://kgv.github.io/rust_book_ru/src/guessing-game.html

> **Методы** похожи на привязанные функции, но доступны только у определённого экземпляра типа, а не самого типа. Мы указали один аргумент функции read_line(): &mut guess.

---
- [ ] http://kgv.github.io/rust_book_ru/src/academic-research.html

> **External uniqueness is unique enough**
> **Scheduling techniques for concurrent systems**
> **Three layer cake**

Думаю тут надо отправить в оригинал

---
- [x] http://kgv.github.io/rust_book_ru/src/traits.html

> Посмотрите главу **Статическая и динамическая диспетчеризация**, чтобы получить больше информации.

---
- [x] http://kgv.github.io/rust_book_ru/src/const-and-static.html

> Они похожи на **постоянные** , но статические значения не встраиваются в место их использования.

---
- [x] http://kgv.github.io/rust_book_ru/src/macros.html

> Если система макросов не может сделать того, что вам нужно, вы можете написать **плагин к компилятору**.

---
- [x] http://kgv.github.io/rust_book_ru/src/raw-pointers.html

> Для более подробной информации об этом обратитесь к главе **FFI**.

---

Написал скриптик(JS), который прошёлся по ссылкам на сайте.
Не уверен, что всё правильно оформил :sweat_smile:

**Comment by mkpankov** [comment]
Спасибо, круто что скриптом это сделал :clap:  Будем работать :+1:

**Comment by mkpankov** [comment]
Про 

> External uniqueness is unique enough
> Scheduling techniques for concurrent systems
> Three layer cake

написал: https://github.com/rust-lang/rust/pull/26662 , https://github.com/rust-lang/rust/issues/26661
