### ISSUE TITLE
Проблемы с отображением EPUB

### ISSUE THREAD

**Issue by mkpankov** [kgv/rust_book_ru#232]
@espdev (из #126 )

> Попробовал открыть Epub-файл на устройстве NOOK. Корректно отображается только первая страница, затем весь текст книги отображается в один столбец слева экрана (столбик текста шириной в одну букву сверху-вниз). При попытке перейти на какую-либо страницу через навигатор вылетает в библиотеку.

**Comment by mkpankov** [comment]
Попробовал смотреть в Calibre (`ebook-view`), FBreader и YotaReader - нигде не воспроизвелось.

Может файл просто битый и его надо перекачать? [Скачайте](https://raw.githubusercontent.com/kgv/rust_book_ru/gh-pages/converted/rustbook.epub), пожалуйста, последнюю версию и попробуйте её.

Нужно больше информации. Появляются ли какие-то ошибки при открытии? Есть ли логи из читалки?

В качестве временного решения. можно попробовать [MOBI](https://raw.githubusercontent.com/kgv/rust_book_ru/gh-pages/converted/rustbook.mobi), хотя я не знаю, поддерживает ли его Nook.

**Comment by espdev** [comment]
Попробовал перекачать файл - не помогло. Ошибок при открытии на экране читалки не появляется. Каких-то логов ошибок в самом устройстве я тоже не нашёл. Книжка понимает только PDF и ePub.

Вот информация об устройстве:

```
NOOK GlowLight
Software version: 1.2.1
Model number: BNRV350
```

Вот как выглядит книга на экране:
![imgp9249](https://cloud.githubusercontent.com/assets/1299189/8796261/0e155494-2f9c-11e5-9021-1134f9db8919.jpg)

**Comment by funkill** [comment]
Попробовал в EBookReader и MoonReader. 
EBookDroid: код отображается примерно символа по 4.
MoonReader: код без отступов и форматирования, ругается на отсутствие шрифтов (возможно получится решить при помощи флага `--embed-all-fonts`).
И в том, и в другом случае переход по ссылкам работает нормально.

**Comment by mkpankov** [comment]
@espdev а попробуйте пожалуйста ещё [эту версию](https://www.gitbook.com/download/epub/book/kgv/rust_book_ru).

У неё свои недостатки, но она может быть по крайней мере читабельна.

**Comment by mkpankov** [comment]
@espdev кстати, а PDF вы не пробовали? Не нравится?

**Comment by mkpankov** [comment]
Я кстати ещё заметил, что наша версия из-под calibre даже на ПК не всю ширину занимает - колонка процентов 40 ширины экрана у меня.

Надо наверное в сторону CSS и задания ширины текста смотреть - возможно что-то с DPI и сопутствующим.

**Comment by espdev** [comment]
@mkpankov Книга по последней вашей ссылке отображается на читалке корректно на всю ширину экрана! :+1: Листинги кода тоже отображаются правильно. Шрифт немного мелкий, заголовки глав отображаются в виде `% Заголовок` но, в общем, всё вполне читабельно, работают ссылки из оглавления в разделы книги.

PDF на читалке не пробовал, потому что у неё слишком маленький экран и обычно PDF-файлы читать не слишком неудобно.

**Comment by mkpankov** [comment]
@espdev прекрасно, будем чинить нашу версию, значит. 

В той, которую вы скачали, в паре мест сломана разметка. Например, в разделах про документацию и тесты. Это ограничение gitbook.

**Comment by espdev** [comment]
@mkpankov Спасибо! Будет здорово, если почините. :)

Посмотрел в раздел "Документация", да кое-где разметка сломалась, но зато я уже пока могу читать другие главы, находясь не за компьютером.

**Comment by mkpankov** [comment]
@espdev вам спасибо за информацию :)

**Comment by mkpankov** [comment]
@espdev подхачил CSS, [попробуйте](https://www.dropbox.com/s/upt0uzajqz5bblb/rustbook.epub?dl=0)

**Comment by espdev** [comment]
@mkpankov Та же проблема - отображается в один столбик букв слева.

**Comment by mkpankov** [comment]
@espdev Понятно. Собираюсь поставить эмулятор Nook'а и с ним экспериментировать.

**Comment by mkpankov** [comment]
Я думаю есть шанс, что с этим надо будет долго возиться. Пока не буду этим заниматься, доделаю редактирование.

**Comment by espdev** [comment]
@mkpankov вообще это не критично, ведь есть планшет, на котором хорошо читается PDF. :)

**Comment by gmax79** [comment]
У меня sony prs-t1 Хочу заметить, что версия книги epub с сайта тоже отображается в одну колонку.Версия из этого топика отображается на всю ширину. Но в обоих книгах вместо букв - знаки вопросов. Видимо нет шрифтов. Включите шрифты в книгу и желательно их поменять на более распространенные.
