### ISSUE TITLE
В EPUB участки с кодом дублируются

### ISSUE THREAD

**Issue by mkpankov** [kgv/rust_book_ru#233]
![http://i.imgur.com/wDzY1wg.png](http://i.imgur.com/wDzY1wg.png)

В Calibre не дублируются, в FBReader дублируются.

**Comment by mkpankov** [comment]
В MOBI всё ок.

**Comment by funkill** [comment]
Calibre заменяет стили на свои, из-за чего отображается код, предназначенный для отправки в playpen (первый, в одну строку, на сайте этот код скрыт). Так же, из-за замены стилей, в конце каждой главы есть оглавление (при генерации pdf, оно скрывается стилями).

**Comment by mkpankov** [comment]
@funkill самое интересное, что в EPUB с gitbook всё ок.

А можно ему сказать стили не заменять?

**Comment by funkill** [comment]
Вчера/сегодня пробовал различные способы добавления/изменения стилей (добавление `--extra-css`, изменение стилей в уже сгенерированной книге, генерирование книги при помощи Sigil и создание epub вручную). Мои попытки не увенчались успехом: ни fbreader, ни ebookdroid не захотели скрывать первый участок кода.

Заметил, что EPUB с Gitbook в EBookDroid код отображает не правильно (в сгенерированном нами EPUB точно такая же картина, только ещё код дублируется)

![screenshot_2015-07-22-15-04-30](https://cloud.githubusercontent.com/assets/4323287/8848740/6edee432-3142-11e5-8f87-90f84657fdcc.png)

**Comment by mkpankov** [comment]
Вот [тут](https://github.com/killercup/trpl-ebook) для оригинала делают ebook в разных форматах. Проблем, с которыми мы тут сталкиваемся, при беглом просмотре, я там не увидел - вроде всё хорошо.

Там используется pandoc & LaTeX вместо calibre, но это возможный вариант.

**Comment by mkpankov** [comment]
Нужно попробовать использовать pandoc как делают по ссылке выше
