### ISSUE TITLE
Перевод «newtype»

### ISSUE THREAD

**Issue by suhr** [kgv/rust_book_ru#258]
Сабж.

**Comment by petrochenkov** [comment]
В том контексте, в котором он в книжке употребляется - обёртка.
Поскольку это жаргон из Хаскеля, то вот для сравения перевод "Learn you a Haskell"
https://books.google.ru/books?id=Ae1YAwAAQBAJ&pg=PA46&source=gbs_toc_r&cad=4#v=onepage&q=newtype&f=false
newtype в основном не переведён, но и обёрткой часто называется.
