### ISSUE TITLE
error-handling.md и std::io

### ISSUE THREAD

**Issue by ithamsteri** [kgv/rust_book_ru#26]
В `error-handling.md` в разделе "Преобразование неудачи в панику" не корректный код. Старый модуль `std::io` изменился и стал `std::old_io`. Теперь этот код не работает:

``` rust
let input = io::stdin().read_line()
                       .ok()
                       .expect("Failed to read line");
```

Теперь строки читаются так:

``` rust
use std::io;

fn main() {
    let mut stdin = io::stdin(); // stdin: Struct std::io::Stdin
    let mut buffer = String::new(); // buffer: Struct std::string::String
    match stdin.read_line(&mut buffer) {
        Ok(size) => {
            println!("Получили: {:?} bytes", size);
            println!("Строка: {:?}", buffer);
        }
        Err(_) => {
            println!("Ошибка");
        }
    }
}
```

**Comment by ithamsteri** [comment]
Можно адаптировать пример в книге так:

``` rust
    let mut buffer = String::new();
    let size = io::stdin().read_line(&mut buffer).ok().expect("Ошибка");
```

**Comment by kgv** [comment]
Я создал пул реквест на измененние в офф документации https://github.com/rust-lang/rust/pull/23933.
Как только появятся изменения в офф документации - внесем их в перевод.

**Comment by kgv** [comment]
Мердж был сделан, при следующем обновлениие до текущего состояния будут внесены изменения в перевод.
