### ISSUE TITLE
Обновить error handling

### ISSUE THREAD

**Issue by mkpankov** [kgv/rust_book_ru#272]

**Comment by mkpankov** [comment]
https://github.com/rust-lang/rust/pull/28301

**Comment by defuz** [comment]
Этим кто-нибудь занимается? Я могу взяться за перевод.

**Comment by mkpankov** [comment]
@defuz пожалуйста. Будем рады изменениям от вас.

**Comment by mkpankov** [comment]
Почти закончили, остался раздел Case Study:

https://doc.rust-lang.org/stable/book/error-handling.html#case-study:-a-program-to-read-population-data

**Comment by vessd** [comment]
https://github.com/rust-lang/rust/pull/30053
