### ISSUE TITLE
Перевод "Hello, world!"

### ISSUE THREAD

**Issue by Slko** [kgv/rust_book_ru#273]
Начал читать с самого начала. Привлекло внимание то, что в разделах "Hello, world!" и "Hello, Cargo!" в половине мест переведено как "Привет, мир!", а в другой половине оставлено "Hello, world!" (в том числе само название раздела).

**Comment by mkpankov** [comment]
Спасибо.

В целом, наверное надо пройтись по использованиям и поредактировать соответственно. Но это не совсем однозначно - "Hello, world!" это устойчивое выражение, для которого есть более-менее устоявшийся русскоязычный перевод. "Hello, Cargo!" - нет. И есть некоторые места, где русский текст всё же недопустим.
