### ISSUE TITLE
Пропуск подразделов, опечатки - c.171, 172 в pdf ("Время жизни")

### ISSUE THREAD

**Issue by dmitry4244** [kgv/rust_book_ru#283]
...
Если вы сравните &mut i32 с &' a mut i32 , то увидите, что они отличаются только
определением времени жизни ' a , написанным между & и mut i32 . &mut i32 читается
как «изменяемая ссылка на i32», а &' a mut i32 — как «изменяемая ссылка на i32 со
временем жизни 'a».

<b>In structs</b> - подзаголовок отсутствует
Вы также должны будете явно указать время жизни при работе с<b>о</b> <b><s>[ struct ][structs]:</s></b> struct:

Подразделы
<b>impl blocks
Multiple lifetimes</b>
отсутствуют.

Пропущен перевод  слова в коде
(глава "Осмысливаем области видимости (Thinking in scopes)") :
...
fn main( ) {
____let y = &5;_______// - + y входит в область видимости
____let f = Foo { x: y }; _// - + f входит в область видимости
_____<b>// stuff</b>_________// |
___________________// |
}__________________// - + f и y выходят из области видимости

**Comment by mkpankov** [comment]
Спасибо!
