### ISSUE TITLE
Опечатки на с. 60 - 76 в pdf

### ISSUE THREAD

**Issue by van-kalsing** [kgv/rust_book_ru#293]
1. с.60: ... адреса будут от 0 до 1 073 741 824 ...
   Должно быть 1 073 741 823, в оригинале так. Однако далее и в переводе и в оригинале используется адрес 2^30, получается неточность. Это, конечно, не мешает пониманию темы, но если кто-то захочет, то может указать на это авторам.
2. с.68 - строка в таблице: "11 f 4". Должно быть "11 f 9"
3. с.76: ... с ожидаемыми результатом

**Comment by vessd** [comment]
на счет первого пункта, в stable версии оригинала все еще присутствуют ошибки с адресами, но в nightly они уже отсутствуют
https://github.com/rust-lang/rust/commit/6d2cb6c688ce0a8aa309236dd04b45149f8eee3c
стоит ли исправлять сейчас или подождать?

**Comment by mkpankov** [comment]
@D101101 я думаю, можно исправлять. Мы строго не синхронизируемся со stable.
