### ISSUE TITLE
Перевести Rustonomicon

### ISSUE THREAD

**Issue by mkpankov** [kgv/rust_book_ru#298]
http://doc.rust-lang.org/nightly/nomicon/

**Comment by suhr** [comment]
Для этого стоит выделить отдельный репозиторий (и заодно создать организацию для переводов).

**Comment by mkpankov** [comment]
@suhr [не вопрос](https://github.com/ruRust/rustonomicon)

**Comment by nick-korsakov** [comment]
Начат ли уже перевод Rustonomicon?
Если да, дайте ссылку на него.

**Comment by suhr** [comment]
@nick-korsakov Нет, но можешь создать PR в https://github.com/ruRust/rustonomicon.
