### ISSUE TITLE
Неочевидности в описании &str в главе про строки (6.17)

### ISSUE THREAD

**Issue by emersceen** [kgv/rust_book_ru#310]
После прочтения главы про строки, сложилось ложное впечатление, что понятия "строковый срез и" "строковый литерал" эквивалентны. Появилась уверенность, что строковые слайсы могут быть только со временем жизни 'static. В дальнейшем возникли проблемы с указанием правильных lifetime'ов. 

Вот ссылка на обсуждение в чате:
https://gitter.im/ruRust/general?at=564660d98b242470793d9051

Возможно есть способ как-то выделить этот момент в книге.

**Comment by defuz** [comment]
Соответствующий баг в оригинальом репозитории: https://github.com/rust-lang/rust/issues/29823
