### ISSUE TITLE
Добавить оригинальные названия терминов при первом упоминании в каждой главе

### ISSUE THREAD

**Issue by defuz** [kgv/rust_book_ru#315]
Добавить к первому упоминанию в каждой главе неоднозначных терминов их расшифровку в круглых скобках на английском языке:
- [ ] borrow
- [ ] ownership
- [ ] moved
- [ ] lifetime
- [ ] pattern matching
- [ ] closure
- [ ] moved closure
- [ ] heap
- [ ] slice
- [ ] tuple
- [ ] enum
- [ ] trait object
- [ ] pattern
- [ ] destructuring
- [ ] exhausive
- [ ] namespace
- [ ] new type
- [ ] arm
- [ ] concurrency
- [ ] dereference

...И возможно другие.

**Comment by neooleg** [comment]
- [x] stack frame (стековый кадр)
  - [Mention #1](https://kgv.gitbooks.io/rust_book_ru/content/src/the-stack-and-the-heap.html)
- [x] raw pointer (сырой указатель)
  - [Mention #1](https://kgv.gitbooks.io/rust_book_ru/content/src/the-stack-and-the-heap.html)
