### ISSUE TITLE
Прикрутить mdbook

### ISSUE THREAD

**Issue by funkill** [kgv/rust_book_ru#331]
Заменить rustbook на [mdbook](https://github.com/azerupi/mdBook)

**Comment by mkpankov** [comment]
Собственно цитата @funkill из нашей переписки:

> недавно наткнулся на реализацию rustbook от azerupi - mdBook (вполне возможно, что ты видел это). Так же нашёл отдельный репозиторий книги, в котором используется данная утилита - https://github.com/rust-lang/book. Как пишет Стив, "This is the next iteration of “The Rust Programming Language”". Решил попробовать сделать тестовую версию с использованием этой утилиты и предложить использовать её вместо rustbook'a. При использовании mdbook книга писется в обычном markdown'e, её можно будет заливать на gitbook и оттуда уже раздавать epub, pdf и mobi (тем более с теми версиями проблем вроде как не возникало, в отличии от тех, которые тенерируются travis'ом). Посмотреть как это выглядит можно тут: http://funkill.github.io/rust_book_ru/INTRODUCTION.html
> 
> единственное отличие с точки зрения читателя, которое вижу - возможность скрыть меню и возможность сменить тему оформления. навигация между предыдущией/следующей главой сделаны по бокам от текста (в текущей версии под текстом). со стороны деплоя и разработки вряд ли что изменится

**Comment by mkpankov** [comment]
Уточнение: использовать gitbook всё же не получится, т.к. он всё ещё не понимает встроенный markdown в документации и примерах.

**Comment by defuz** [comment]
Насколько я помню, на mdBook рано или поздно должна будет перейти "официальная" книга.
