### ISSUE TITLE
Todo if.md

### ISSUE THREAD

**Issue by kgv** [kgv/rust_book_ru#34]
- [x] if`->`if`
  https://github.com/kgv/rust_book_ru/pull/33/files#diff-fb4de66872c8e3d29666fedc2315e187R11
- [x] выраажение -> выражение
  https://github.com/kgv/rust_book_ru/pull/33/files#diff-fb4de66872c8e3d29666fedc2315e187R27
- [x] ибтным -> битным
  https://github.com/kgv/rust_book_ru/pull/33/files#diff-fb4de66872c8e3d29666fedc2315e187R130
- [x] ~~единичный тип?~~ + правильным -> корректным
  https://github.com/kgv/rust_book_ru/pull/33/files#diff-fb4de66872c8e3d29666fedc2315e187R147
- [x] когда вы увидите -> когда вы не увидите
  https://github.com/kgv/rust_book_ru/pull/33/files#diff-fb4de66872c8e3d29666fedc2315e187R155
- [ ] подкорректировать стилистику

**Comment by funkill** [comment]
Когда назвал "единичным типом", опирался на следующую статью: http://habrahabr.ru/post/207126/

> Единичные типы данных не дают ничего, кроме знания о том, что он есть.
> Из распространённых типов данных используются
> data () = ()      --X
> ...
> Почти во всех программах, используется подпись:
> main :: IO ()
> потому что программа должна что-то возвращать. Поэтому () является самым популярным типом, когда надо возвращать ничего.

**Comment by mkpankov** [comment]
В Пирсе (Типы в языках программирования) применяют "тривиальное значение" в качестве перевода для "unit".

Кстати, не уверен, что хорошо переводить "signature" как "подпись".

**Comment by kgv** [comment]
Да, [в вики](https://ru.wikipedia.org/wiki/%D0%90%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B0%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D1%82%D0%B8%D0%BF_%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85) тоже используется "единичный элемент".

А "signature" я бы переводил как [сигнатура](https://ru.wikipedia.org/wiki/%D0%A1%D0%B8%D0%B3%D0%BD%D0%B0%D1%82%D1%83%D1%80%D0%B0) по-моему уже достаточно устаканившийся термин в IT.

**Comment by mkpankov** [comment]
@kgv согласен с обоими предложениями.
