### ISSUE TITLE
Неправильное отображение сигнатуры функции в главе "Обработка ошибок".

### ISSUE THREAD

**Issue by HaruAtari** [kgv/rust_book_ru#342]
В [этом разделе](https://github.com/kgv/rust_book_ru/blob/master/src/error-handling.md#the-limits-of-combinators)  в первом примере кода есть такой участок в сигнатуре функции

![rust_book_ru_error-handling md at master c2 b7 kgv_rust_book_ru - google chrome 2016-01-12 23 47 38](https://cloud.githubusercontent.com/assets/3523420/12276471/fc4e8ca6-b986-11e5-900d-a6726f591cb4.png)

А в [скомпилированной книге](https://kgv.gitbooks.io/rust_book_ru/content/src/error-handling.html#ограничения-комбинаторов) от него осталась только закрывающая скобка.

![1](https://cloud.githubusercontent.com/assets/3523420/12276513/4e7428f6-b987-11e5-9d34-ffc1bea25519.png)

**Comment by mkpankov** [comment]
Попробуйте версию rustbook: http://kgv.github.io/rust_book_ru/src/error-handling.html#the-limits-of-combinators

К сожалению, у gitbook много проблем с разметкой в том виде, как она используется в книге.

**Comment by vessd** [comment]
@mkpankov зачем у нас вообще ссылка на gitbook?

**Comment by mkpankov** [comment]
@D101101 он иногда генерирует файлы, которые лучше работают на читалках. Например, [здесь](https://github.com/kgv/rust_book_ru/issues/232#issuecomment-123459670)
