### ISSUE TITLE
PDF a5

### ISSUE THREAD

**Issue by gmax79** [kgv/rust_book_ru#344]
Было бы замечательно если  сделаете книгу в формате pdf a5. Хорошо их читать на электронных книгах. Сейчас издательства выпускают свои книги чаще всего в данном формате. С этим форматом меньше всего проблем возникает. a4 просто не помещаются на экран ридера.

**Comment by mkpankov** [comment]
Данный репозиторий более не [поддерживается](https://github.com/kgv/rust_book_ru/blob/master/README.md).

Я создал [задачу](https://github.com/ruRust/rust_book_ru/issues/20) в новом, закрываю эту.
