### ISSUE TITLE
Опечатки

### ISSUE THREAD

**Issue by rafuck** [kgv/rust_book_ru#345]
Неплохо было бы сделать в web-версии книги быстрый отчет о найденной опечатке (например, об орфографической или грамматической ошибке). Вести список неудобно и потому не хочется. А так выделил текст, нажал "ctrl+enter" и все довольны.

**Comment by mkpankov** [comment]
Согласно [сообщению](https://github.com/kgv/rust_book_ru/blob/master/CONTRIBUTING.md) о переезде, задачи больше не принимаются здесь.
