### ISSUE TITLE
В html версии не работает меню 三 для "узкого экрана"

### ISSUE THREAD

**Issue by ghost** [kgv/rust_book_ru#348]
![image](https://pp.vk.me/c626216/v626216332/17254/IDodVl3MFBU.jpg)

FF 44.0, Ubuntu

**Comment by mkpankov** [comment]
Эта версия книги не поддерживается. Актуальная [здесь](http://rurust.github.io/rust_book_ru/). Меню там работает.

**Comment by ghost** [comment]
Но я об этой книге и писал. Если перейти с линка что Вы дали [сюда](http://rurust.github.io/rust_book_ru/src/primitive-types.html), то меню не работает у меня.

**Comment by mkpankov** [comment]
Спасибо, про это уже есть [issue](https://github.com/ruRust/rust_book_ru/issues/28)
