### ISSUE TITLE
Оригинал книги будет сильно изменён

### ISSUE THREAD

**Issue by mkpankov** [kgv/rust_book_ru#35]
Вчера в беседе на IRC канале #rust steveklabnik (основной технический писатель) сказал, что он будет сильно реорганизовывать и редактировать книгу на следующей неделе (https://botbot.me/mozilla/rust/msg/35832655/).

Помимо этого, документация в принципе будет стабилизироваться/дополняться перед релизом 1.0.

В контексте этого, возможно стоит отложить большую работу по редактированию/окончанию перевода, поскольку через 6 недель его придётся переписывать чтобы синхронизировать с оригиналом.

**Comment by kgv** [comment]
Спасибо. Не догадался узнать у Стива о планах на доки. Поддерживаю, думаю стоит подождать.

PS Зато теперь я хоть понял более-менее воспринимаемый аналог "feature gate" - закрытые фичи/возможности (на данный момент закрытые)

**Comment by mkpankov** [comment]
@kgv да я тоже случайно узнал. Пошёл поспрашивать про аналоги "feature gate" в других языках, чтобы понять, как лучше перевести, а он увидел и предупредил :)

**Comment by mkpankov** [comment]
Кстати, перечитал лог - он сказал не "на следующей неделе", а "следующие недели". Видимо речь шла о предрелизных 6 неделях (т.к. релиз Rust 1.0 final намечен на 15 мая).

**Comment by kgv** [comment]
Стив начал [большие изменения в документации](https://github.com/rust-lang/rust/commit/0027253f188cb6986f4d1281a31bb01769178f7d). До конца недели понаблюдаю за тенденциями изменений и приступлю к переводу.
