### ISSUE TITLE
Правила

### ISSUE THREAD

**Issue by kgv** [kgv/rust_book_ru#37]
## Правила разметки
- **Ширина текста** - 80.
## Правила перевода
- **Текст в примерах кода** - переводится. [^0]
- **Сообщения об ошибках компилятора** - не переводятся.
- **Специальные markdown заголовки в док-комментариях к коду Rust** (например `# Examples`) - не переводятся. [^1]
- **Цитаты**
  - **"Декоративные" цитаты** - заменять аналогичными по смыслу русскоязычными (при их наличии).
  - **"Cмысловые" цитаты** (несут в себе некий смысл, на который опирается дальнейшее повествование) - переводить близко к тексту.
- **Имена модулей, функций, переменных**
  - **В примерах** - не переводятся
  - **В сопроваждающем тексте** - если это улучшает восприятие, при первом упоминании пишем перевод один раз в скобках.
- **Термины**
  - Стараемся подобрать русское слово, наиболее подходящее по контексту. При вводе русского термина стоит один раз привести оригинальный термин в скобках. Например, контейнер (crate).

[^0]: Тонкий момент: не стоит переводить имена вроде Graydon и Niko как Григорий и Николай - это отсылка к создателям языка
[^1]: В [разделе о документации](https://github.com/rust-lang/rust/blob/master/src/doc/trpl/documentation.md#special-sections) сказано, что они не являются частью синтаксиса, но являются соглашением.
## Правила пунктуации
- **"Одинарные кавычки"** - `‘` и `’` заменяются на **"Двойную кавычку (универсальная)"** - `"`.
## Правила синтаксиса
- Буква "ё" используется везде, где этого требуют правила русского языка.
## Правила для ссылок

**Относительные** ссылоки на API документацию Rust заменяются на **абсолютные**. 
По умолчанию следует использовать ссылки на стабильную версию (http://doc.rust-lang.org/std/primitive.bool.html), если же ссылка на фичу из нестабильной версии, то добавляем nightly (http://doc.rust-lang.org/nightly/std/primitive.bool.html).
## Словарь терминов

aliasing -> задание псевдонимов, псевдонимизация/совпадение, совпадающий указатель? (в отношении указателей, ссылок)
borrowing -> заимствование
box -> упаковка
capacity -> ёмкость (в отношении векторов)
crate -> контейнер
destructure -> деконструкция/разбор?
length -> длина (в отношении векторов)
lifetime -> время жизни
match -> сопоставление с образцом
matcher ->
matching ->
module -> модуль
operator -> операция
ownership -> владение, владение ресурсом, право владения
slice -> срез
statement -> оператор
trait -> типаж
tuple struct -> кортежная структура
variable binding -> имя (связанное имя) / значение (связанное значение) в зависимости от контекста.
unit type -> единичный тип

**Если у вас есть вопросы или предложения по правилам - не стесняйтесь, обязательно предлагайте лучшие на ваш взгляд варианты!**

**Comment by mkpankov** [comment]
Моё мнение:

Во всех случаях термины должны переводиться "один к одному", т.е. использоваться везде должно одно и то же русское слово, а не различные синонимы.
Aliasing в случае указателей хорошо переводится как "совпадение". Aliased pointer - "совпадающий указатель".
Borrowing - предлагаю "заимствование", потому что нет такой сильной ассоциации с деньгами.
Life time - "время жизни" меньше режет слух.
Ownership - "владение" является одновременно нейтральным и коротким. "Владение ресурсом", "владение памятью" звучит нормально, в отличие от других альтернатив :)
Destructuring по-моему хорошо описывается словом "разбор", особенно в контексте частого применения этой возможности в реализации различных парсеров.

**Comment by kgv** [comment]
@mkpankov я тоже придерживаюсь мнения, что стоит для одного и того же оригинального термина использовать единственный термин перевода :+1: . Однако такие вариации как "владение" и "право владения" (напримен в контексте "move ownership" - отдает право влажения) считаю приемлемыми.
borrowing -> заимствование, заем считаю подходят оба, ~~одолжить~~
match -> сопоставление с образцом можно ли также использовать "шаблон" вместо "образец"?
matcher -> образец/шаблон/сопоставитель?
matching -> сопоставление?
destructuring -> не вяжется у меня данное действие в Rust с термином "разбор" почему-то... У меня оно однозначно ассоциируется с "деструктуризацией" или "деконструкцией", но деструктуризация может неправильно ассоциироваться со структурами.
aliasing -> да, во многоих контекстах по отношению к указателям и ссылкам "совпадение" хорошо звучит. Единственное - "have no guarantees about aliasing or mutability" - как тогда следует переводить?

**Comment by mkpankov** [comment]
> Единственное - "have no guarantees about aliasing or mutability" - как тогда следует переводить?

Думаю, там в контексте надо переводить.

**Comment by mkpankov** [comment]
Новый термин: trait.

Википедия переводит его как ["типаж"](https://ru.wikipedia.org/wiki/%D2%E8%EF%E0%E6_%28%E0%E1%F1%F2%F0%E0%EA%F2%ED%FB%E9_%F2%E8%EF%29).

На Хабре в ряде статей также используется этот термин: http://habrahabr.ru/search/?q=trait&target_type=posts&order_by=relevance

В принципе он неплох и слух вроде не режет. Единственное, что меня смущает - его возможное столкновение с "типажом", который kind.

**Comment by suhr** [comment]
Вот ещё перевод rustbyexample.com: https://github.com/suhr/rust-by-example, можно посмотреть, какие термины там.

И да trait — типаж, slice — срез, ownership — владение, а borrowing — заимствование.
Правда crate всё-таки крэйт.

**Comment by suhr** [comment]
> capacity -> мощность (в отношении векторов)

Ёмкость же. Т.е сколько элементов вместится без необходимости выделить память.

> match -> сопоставление с шаблоном

Сопоставление с образцом, устоявшийся термин.

**Comment by mkpankov** [comment]
variable binding - предлагаю "имя" или "значение" в зависимости от контекста.
или лучше "связанное имя"

**Comment by suhr** [comment]
tuple struct → кортежная структура

**Comment by kgv** [comment]
> Единственное, что меня смущает - его возможное столкновение с "типажом", который kind.

Думаю kind тогда стоит переводить как тип, чтобы различать эти 2 понятия.

> Сопоставление с образцом, устоявшийся термин.

Просто в документации затем присутствуют термины `Box Syntax Patterns`, `Slice Patterns` и т.д. а переводить их как "образцы срезов" не камильфо.

> variable binding - предлагаю "имя" или "значение" в зависимости от контекста.
> или лучше "связанное имя"

Согласен, связанное имя или связанное значение в зависимости от контекста.

> Правда crate всё-таки крэйт.

Тогда почему слайсы, туплы, трейты и паттерн-матчинг не оставить? Я склоняюсь все-таки к контейнеру. (к тому же очень канонично такой термин вписывается в cargo)

**Comment by mkpankov** [comment]
> Думаю kind тогда стоит переводить как тип, чтобы различать эти 2 понятия.

Но "тип" - это type :) Википедия использует для kind ["род"](https://ru.wikipedia.org/wiki/%D0%A0%D0%BE%D0%B4_%28%D1%82%D0%B5%D0%BE%D1%80%D0%B8%D1%8F_%D1%82%D0%B8%D0%BF%D0%BE%D0%B2%29).

Предлагаю пока переводить основываясь на эти основные понятия, раз у них есть канонический перевод. Как переводить higher-kinded types подумаем потом :) (высокородные типы, ахаха!)

> Просто в документации затем присутствуют термины Box Syntax Patterns, Slice Patterns и т.д. а переводить их как "образцы срезов" не камильфо.

Но и как "шаблоны срезов" тоже. Думаю, для самого сопоставления с образцом надо использовать канонический перевод, а для всяких заморочных вещей потом что-то придумаем.

> Тогда почему слайсы, туплы, трейты и паттерн-матчинг не оставить? Я склоняюсь все-таки к контейнеру. (к тому же очень канонично такой термин вписывается в cargo)

Согласен, контейнер нормально подходит. Я думаю в rustbyexample crate был оставлен просто из-за отсутствия канонического перевода.

**Comment by suhr** [comment]
> Тогда почему слайсы, туплы, трейты и паттерн-матчинг не оставить? Я склоняюсь все-таки к контейнеру. (к тому же очень канонично такой термин вписывается в cargo)

Потому, что контейнер это таки контейнер ([тыц](https://en.wikipedia.org/wiki/Container_%28abstract_data_type%29), [тыц](https://en.wikipedia.org/wiki/Container_%28type_theory%29), [тыц](https://en.wikipedia.org/wiki/Container_%28virtualization%29), [тыц](https://en.wikipedia.org/wiki/Digital_container_format), [тыц](https://en.wikipedia.org/wiki/Web_container)), когда же крэйт — единица сборки в Rust. Слишком много всего зовётся словом «контейнер», и ничего из того, что близко к теме.

**Comment by mkpankov** [comment]
> Потому, что контейнер это таки контейнер (тыц, тыц, тыц, тыц, тыц), когда же крэйт — единица сборки в Rust. Слишком много всего зовётся словом «контейнер», и ничего из того, что близко к теме.

Но если бы это было проблемой, другие люди тоже не называли бы новые непохожие сущности словом "контейнер".

Я не видел, чтобы первые два значения употреблялись в Rust. Для этих вещей они обычно используют "data structure", "struct", "enum", "sum type", "sequence" и подобное.

Вот, например, употребления "container" в оригинале TRPL:

```
➜  trpl git:(master) grep -irne 'container' .
➜  trpl git:(master)
```

Всё остальное вообще не относится к делу.

Crate как одновременно единица компиляции и единица распространения (пакет) это вообще не изобретение Rust ли?

**Comment by mkpankov** [comment]
К слову: мне кажется, для обсуждения перевода отдельных терминов, если он спорный, надо создавать отдельные задачи, иначе в комментариях к этой скоро будет не продраться.

**Comment by suhr** [comment]
> Но если бы это было проблемой, другие люди тоже не называли бы новые непохожие сущности словом "контейнер".

Вот поэтому разработчики Rust и назвали новую сущность как crate, а не как container.

> Crate как одновременно единица компиляции и единица распространения (пакет) это вообще не изобретение Rust ли?

Это же фича Cargo, а не самого Rust, разве нет?

**Comment by mkpankov** [comment]
> Это же фича Cargo, а не самого Rust, разве нет?

Я имел ввиду экосистему языка. Компилятор тоже оперирует этим понятием, раз это единица компиляции.

> Вот поэтому разработчики Rust и назвали новую сущность как crate, а не как container.

А вот этого мы не знаем.

**Comment by mkpankov** [comment]
Как всё-таки переводим unit?

Варианты: пустой кортеж, единичное значение, тривиальное значение.

**Comment by suhr** [comment]
Ну, unit type повсеместно зовётся «единичным типом», так что естественно называть unit «единичным значением» или «значением единичного типа».

**Comment by mkpankov** [comment]
Вообще в описании [кортежа](https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D1%80%D1%82%D0%B5%D0%B6_%28%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D0%B0%29) говорится, что если он с нулевым числом элементов, то это пустое множество. По сути то же самое, что и единичный тип, но более интуитивно.

**Comment by suhr** [comment]
Это как кортеж определяется в математике. В программировании же нет множеств, но есть типы.
Единичный тип — это тип с единственным возможным значением. Пустой кортеж — лишь стандартный вариант подобного типа, но не единственный.
Кроме того, есть ещё и _пустой (низший) тип_. У пустого типа вообще нет допустимых значений, экземпляр пустого типа невозможно создать. Хотя этот тип не встречается в обычных языках, он играет важную роль в языках с зависимыми типами.

**Comment by kgv** [comment]
Добавил unit type -> единичный тип
Если есть критика по поводу данного варианта перевода - думаю стоит создать отдельную issue.

**Comment by kgv** [comment]
Ввел новое правило пунктуации:

> **"Одинарные кавычки"** - `‘` и `’` заменяются на **"Двойную кавычку (универсальная)"** - `"`.

В связи с [обсуждением](https://github.com/kgv/rust_book_ru/pull/66/files)

**Comment by kgv** [comment]
Новое правило для ссылок на API документацию Rust.

> Относительные ссылоки на API документацию Rust заменяются на абсолютные.

**Comment by kgv** [comment]
Добавил:

> box -> упаковка

**Comment by mkpankov** [comment]
Закрываю.

Для дальнейшего обсуждения существующих правил или новых предложений следует создавать новые задачи.
