### ISSUE TITLE
Ход выполнения перевода

### ISSUE THREAD

**Issue by kgv** [kgv/rust_book_ru#38]
**Если вы беретесь за работу над каким-нибудь файлом, просьба отписаться здесь.**

**перевод идет** - работа над переводом ведется.
**перевод окончен в черновом варианте** - требуется редактирование семантики.
**перевод окончен в чистовом варианте** - требуется редактирование орфографии, грамматики и стилистики.
- [x] academic-research.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] advanced-linking.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] associated-constants.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] associated-types.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] attributes.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] benchmark-tests.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] borrow-and-asref.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] box-syntax-and-patterns.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] casting-between-types.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] closures.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] comments.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] compiler-plugins.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] concurrency.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] conditional-compilation.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] const-and-static.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] crates-and-modules.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] deref-coercions.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] dining-philosophers.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] documentation.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] drop.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] effective-rust.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] enums.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] error-handling.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] ffi.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] for-loops.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] functions.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] generics.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] getting-started.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] glossary.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] guessing-game.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте. 
- [x] hello-cargo.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] hello-world.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] if-let.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] if.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] inline-assembly.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] installing-rust.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] intrinsics.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] iterators.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] lang-items.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] learn-rust.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] lifetimes.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] macros.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] match.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] method-syntax.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] mutability.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] nightly-rust.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] no-stdlib.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] operators-and-overloading.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] ownership.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] patterns.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] primitive-types.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] README.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] raw-pointers.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] references-and-borrowing.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] release-channels.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] rust-inside-other-languages.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] slice-patterns.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] strings.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] structs.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] SUMMARY.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] syntax-and-semantics.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] testing.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] the-stack-and-the-heap.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] trait-objects.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] traits.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] tuple-structs.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] type-aliases.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] ufcs.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] unsafe.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] unsized-types.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] variable-bindings.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] vectors.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.
- [x] while-loops.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.

**Comment by mkpankov** [comment]
- [ ] unsized-types.md
  - [x] перевод окончен в черновом варианте

**Comment by mkpankov** [comment]
- [x] const-and-static.md
  - [x] перевод окончен в черновом варианте

**Comment by mkpankov** [comment]
debug-and-display.md был удалён

**Comment by mkpankov** [comment]
- [x] deref-coercions.md
  - [x] перевод идёт

**Comment by mkpankov** [comment]
- [x] deref-coercions.md
  - [x] перевод закончен в черновом варианте

**Comment by mkpankov** [comment]
- [x] if-let.md
  - [x] перевод закончен в черновом варианте

**Comment by mkpankov** [comment]
- [x] mutability.md
  - [x] перевод начат

**Comment by funkill** [comment]
- [x] guessing-game.md
  - [x] перевод начат

**Comment by Rastopyr** [comment]
- [x] unsave-code.md
  - [x] перевод идет(орфография, семантика)

**Comment by ithamsteri** [comment]
- [ ] the-stack-and-the-heap.md
    - [x] перевод начат

**Comment by mkpankov** [comment]
- [x] drop.md
  - [x] перевод начат

**Comment by kgv** [comment]
- [x] borrow-and-asref.md
  - [x] перевод идет.

**Comment by mkpankov** [comment]
- [x] drop.md
  - [x] перевод закончен в черновом варианте

**Comment by ithamsteri** [comment]
- [x] type-aliases.md
  - [x] перевод идет.
  - [x] перевод окончен в черновом варианте.

**Comment by Rastopyr** [comment]
- [x] unsave-code.md
  - [x] перевод закончен в черновом варианте(орфография, семантика)

**Comment by kgv** [comment]
тест

**Comment by kgv** [comment]
тест

**Comment by mkpankov** [comment]
- [ ] macros.md
  - [x] перевод идёт

**Comment by kgv** [comment]
- [ ] rust-inside-other-languages.md
  - [x] перевод идёт

**Comment by ithamsteri** [comment]
- [x] **dining-philosophers.md**
  - [x] перевод окончен в черновом варианте.
  - [x] перевод окончен в чистовом варианте.

**Comment by mkpankov** [comment]
- [ ] macros.md
  - [x] перевод окончен в черновом варианте
- [ ] compiler-plugins.md
  - [x] перевод начат

**Comment by kgv** [comment]
- [ ] inline-assembly.md
  - [x] перевод начат

**Comment by mkpankov** [comment]
- [ ] compiler-plugins.md
  - [x] перевод окончен в черновом варианте

**Comment by mkpankov** [comment]
- [ ] lang-items.md
  - [x] перевод начат

**Comment by mkpankov** [comment]
- [ ] lang-items.md
  - [x] перевод закончен в черновом варианте

**Comment by mkpankov** [comment]
Если верить этой задаче, то за исключением конца `guessing-game.md`, у нас всё переведено

**Comment by mkpankov** [comment]
Вычитываю `src/README.md`, `getting-started.md`, `installing-rust.md`, `hello-world.md`, `hello-cargo.md`.

**Comment by kgv** [comment]
Вычитываю раздел "learn-rust.md", "dining-philosophers.md", "rust-inside-other-languages.md".
Угадайку оставил на случай, если у @funkill имеется уже завершенный вариант, и он успеет его выложить до окончания вычитывания.

**Comment by mkpankov** [comment]
Вычитываю `effective-rust.md`, `the-stack-and-the-heap.md`

**Comment by mkpankov** [comment]
Вычитываю `testing.md`

**Comment by mkpankov** [comment]
Вычитываю `conditional-compilation.md`

**Comment by mkpankov** [comment]
Вычитываю `documentation.md`

**Comment by mkpankov** [comment]
Вычитываю `iterators.md`

**Comment by mkpankov** [comment]
Вычитываю `concurrency.md`

**Comment by mkpankov** [comment]
Вычитываю `error-handling.md`

**Comment by mkpankov** [comment]
Аудит закончен, сделал отдельные задачи на то что надо сделать, эту закрываю
