### ISSUE TITLE
Лишние скобки

### ISSUE THREAD

**Issue by ithamsteri** [kgv/rust_book_ru#4]
Вот если посмотреть на этот коммит https://github.com/rust-lang/rust/commit/f49fd40f208827798ccd91394e3a3986c8bc6886, то фигурные скобки не так важны. Думаю что можно их удалить во всех файлах.

**Comment by kgv** [comment]
Согласен, судя по коммиту, фигурные скобки не обязательны для одиночных опций кода. Хотя это не критично. Думаю, буду удалять по мере удаления их из исходных документов.

**Comment by ithamsteri** [comment]
Хотя попадались мне вот такие конструкции:
    ```{rust, ignore}
Даже не знаю, что это значит.

**Comment by kgv** [comment]
Я же говорю: "для одиночных опций кода". Эти конструкции скорее всего обрабатываются парсером http://www.gitbook.io/, через который создается и хостится книга. Хотя я не разбирался в этом досконально пока.

**Comment by kgv** [comment]
При переводе раздела про макросы сталкнулся и с такими флагами для кода в markdown:

`````` markdown
```rust,ignore
...
``````

Так что и не одиночные флаги (опции) не требуют фигурных скобок. Зачем эти фигурные скобки - хз, насколько мне известно - они не характерны для markdown.

**Comment by kgv** [comment]
ignore - это [специальная директива rustdoc](https://github.com/rust-lang/rust/blob/master/src/doc/trpl/documentation.md#running-documentation-tests).
Правда в [конвенции](https://github.com/rust-lang/rfcs/blob/master/text/0505-api-comment-conventions.md) не упоминается о фигурных скобках и случаях их использования.

**Comment by kgv** [comment]
Добавил [правила перевода](https://github.com/kgv/rust_book_ru/blob/master/RULES.md)
