### ISSUE TITLE
Перевод unit type

### ISSUE THREAD

**Issue by mkpankov** [kgv/rust_book_ru#68]
Согласно переводу unit type - 'единичный тип', unit - 'единичное значение'. 
Получается странно в файле [guessing-game.md](https://github.com/kgv/rust_book_ru/commit/2ee6fa2af86cbe55c1bf07af126a4158f86b78fb#diff-0d12477373c921de81be610be3f4cc55R117):

> Из-за того, что мы не указали тип возвращаемого значения, предполагается, что будет возвращаться `()` - пустой [кортэж][tuples].

Ссылка ведёт на кортежи[tuples]. Причём тут кортеж, если мы говорим о единичном значении?

Нужно либо вводить термин в разделе о кортежах и в глоссарий, либо переводить всё-таки как пустой кортеж (потому что так в оригинале).

**Comment by suhr** [comment]
А как оригинал сочетает «empty tuple» c «unit type»?

**Comment by mkpankov** [comment]
> Because
> we didn’t include a return type, it’s assumed to be `()`, an empty
> [tuple][tuples].

**Comment by suhr** [comment]
Я имею в виду, что оригинал должен был пояснить связь между «empty tuple» и «unit type», потому что, вообще говоря, это разные вещи.

**Comment by mkpankov** [comment]
Ну, может и так, но, как видите, он этого не делает, и называет `()` 'empty tuple'.

В конечном-то счёте ошибки в оригинале это тоже наши проблемы. Надо просто решить, что с этим делать.

**Comment by suhr** [comment]
Нужно добавить сноску с пояснением, ну и в глоссарий термин ввести.

**Comment by kgv** [comment]
Я думаю правильнее всего будет вынести этот вопрос на уровень оригинала, то есть задать вопрос в irc или в issue о том как правильно воспринимать "()" в рамках Rust - как «empty tuple» или как «unit type». В выходные сделаю это. Если кто-то сделает сделает это раньше, просьба отписаться тут.

**Comment by mkpankov** [comment]
[Что говорят в IRC](https://botbot.me/mozilla/rust/msg/38649946/)

Я с ними согласен, ради этого одного случая вводить целое понятие смысла нет. В информатике кортеж длины ноль - это пустое множество. Пустое множество - это ничего. Никаких смысловых проблем с тем, что функция, возвращающая "ничего", возвращает "пустой кортеж", нет.

**Comment by mkpankov** [comment]
Ну и вот, в довершение:
http://en.wikipedia.org/wiki/Tuple#Names_for_tuples_of_specific_lengths

**Comment by suhr** [comment]
> В информатике
> множество

Here we go again.

> Никаких смысловых проблем с тем, что функция, возвращающая "ничего", возвращает "пустой кортеж", нет.

Как и нет проблем с тем, чтобы называть unit type «единичным типом», следуя за оригиналом.

Да, и:

> The unit type is useful even in functions without side effects if the programming language supports algebraic data types. **Any nullary data constructor is effectively isomorphic with the unit type.** One can solve the semipredicate problem (the problem of distinguishing between a "normal" return value of a function and an "error") elegantly in such a language, by encoding the "error" as the unit type. In Haskell, the polymorphic type Maybe is predefined for this purpose. Here Nothing is isomorphic to the unit type:
> 
> ``` .haskell
> data Maybe a = Nothing | Just a`
> ```

http://en.wikipedia.org/wiki/Unit_type

**Comment by mkpankov** [comment]
> Как и нет проблем с тем, чтобы называть unit type «единичным типом», следуя за оригиналом.

В оригинале используют 'empty tuple'.

**Comment by suhr** [comment]
> В оригинале используют 'empty tuple'.

Где empty tuple, там «пустой кортеж». Где unit type, там «единичный тип».

**Comment by mkpankov** [comment]
Обсуждение оригинала TRPL:

https://github.com/rust-lang/rust/issues/25244
