### ISSUE TITLE
Заголовок верхнего уровня начинается с `%`

### ISSUE THREAD

**Issue by kgv** [kgv/rust_book_ru#7]
Думаю стоит добавить вопрос о заголовке верхнего уровня, который начинается с `%`. У меня было подозрение, что эту нехарактерную для markdown разметку должен обрабатывать парсер [gitbook](https://github.com/GitbookIO/gitbook). Но, после сборки [книги](http://kgv.gitbooks.io/rust_book_ru/content/) в сервисе http://www.gitbook.io/, `%` так остался.

**Comment by funkill** [comment]
По всей видимости, документацию собирают при помощи rustdoc: на страницах документации указан следующий генератор: `<meta name="generator" content="rustdoc">`. В главе ["Документация"](http://doc.rust-lang.org/nightly/book/documentation.html#other-documentation) сказано, что заголовок в markdown файлах, которые будут обрабатываться rustdoc'ом, должен начинаться с `%` и быть самой первой строчкой файла.

**Comment by kgv** [comment]
Посмотрел сейчас - все верно. Я почему-то был уверен, что для сборки gitbook используется, наверно с Rust by Example перепутал.
Спасибо, вопрос закрыт.
