### ISSUE TITLE
очепятка в "Обработка предположения"

### ISSUE THREAD

**Issue by 4Lila** [kgv/rust_book_ru#73]
Давайте разберём этот участок ьит за битом.

и я б выразился не так: "Реализация игры угадайка"

**Comment by 4Lila** [comment]
далее "Изначально Rust импортирует лишь некоторые вещи в нашу программ, в так   называемом вступлении."

некоторые вещи ? какие?
*программу
вступлении? заглавие, начале, инициализации?

**Comment by mkpankov** [comment]
Спасибо за замечания!

> Давайте разберём этот участок ьит за битом.

Это уже переформулировали.

> и я б выразился не так: "Реализация игры угадайка"

Не понял, к какому месту относится данный комментарий.

> некоторые вещи ? какие?

Подумаем, как переписать это место.

> вступлении? заглавие, начале, инициализации?

Мы не смогли придумать, как лучше перевести "prelude". Вы можете что-то предложить?

**Comment by 4Lila** [comment]
Обработка предположения -> Реализация игры угадайка (какой вариант будет по русски?)

prelude - так лучше и оставить, все категориальные вещи лучше не трогать. (prelude) понятнее, чем любой перевод, тем более в доках по языку программирования. А перевод: прединициализация - тоже калька.

**Comment by mkpankov** [comment]
Если я правильно вас понял, вы предлагаете поменять "Обработка предположения" на "Реализация игры угадайка". 

На это я вам отвечу: "Обработка предположения" - это более узко; это часть реализации игры "угадайка".

> prelude - так лучше и оставить, все категориальные вещи лучше не трогать. (prelude) понятнее, чем любой перевод, тем более в доках по языку программирования. А перевод: прединициализация - тоже калька. 

Не могу согласиться. Мотивы выходят сильно за рамки обсуждения в этом формате, но в общем мы не переводим только совсем устоявшиеся термины, вроде слова "стек".

Прецедент удачного перевода специального термина Rust есть - "crate" хорошо переводится как "контейнер" с сохранением и смысла, и коннотаций.
