### ISSUE TITLE
Перенесение правил в Wiki репозитория

### ISSUE THREAD

**Issue by funkill** [kgv/rust_book_ru#78]
Предлагаю перенести правила в wiki репозитория и разделить всё, что сейчас там имеется на две статьи: непосредственно сами правила и словарь терминов. 
За счёт этого не надо будет просматривать все коммертарии задачи #37 для получения полной картины о правилах. Для отдельных правил можно указывать ссылки на задачи, из текста которых можно получить представление о том, почему было создано данное правило.

**Comment by kgv** [comment]
:+1:

[Правила](https://github.com/kgv/rust_book_ru/wiki/%D0%9F%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0)
[Словарь терминов](https://github.com/kgv/rust_book_ru/wiki/%D0%A1%D0%BB%D0%BE%D0%B2%D0%B0%D1%80%D1%8C-%D1%82%D0%B5%D1%80%D0%BC%D0%B8%D0%BD%D0%BE%D0%B2)

**Comment by mkpankov** [comment]
О, сам то же самое хотел предложить.

Наверное, закрываю.
