### ISSUE TITLE
Соответствие коммитам оригинальной книги

### ISSUE THREAD

**Issue by funkill** [kgv/rust_book_ru#79]
Предлагаю создать файл/задачу/страницу на wiki где для каждого файла перевода будет указан коммит в оригинальной книге на момент последнего перевода файла.
Для чего это может быть полезно: при изменении файла в оригинальной книге, мы будем занать с какой версией надо сравнить изменения. На основании увиденных различий можно принимать решение, стоит ли вносить изменения (может быть там просто исправлялись опечатки) и в каких местах их вносить.

**Comment by mkpankov** [comment]
У меня появлялись мысли, что, возможно, надо сделать какой-то скрипт, который будет по информации из git всё это понимать.

Но я пока не продумал что же надо понимать и в каком случае это надо делать.

**Comment by kgv** [comment]
Я согласен с идеей, но пока не знаю какой вариант тут подойдет... Добавлять еще один список - хз. Можно за правило взять в каждом коммите добавлять что-то типа `original commit xxxx`

Скрипт... хм...
Я не представляю как скриптом определить какой коммит был взят за основу перевода... если только процент соответствия исходных кодов. Но это не будет работать в 100% случаях, у нас ведь переводятся примеры.

**Comment by mkpankov** [comment]
Я пока в режиме мозгового штурма буду писать свои соображения, может вместе до чего-то додумаемся:

По смыслу, наш перевод - это ветка оригинальной книги. Это ветка, которая не будет вливаться обратно (по крайней мере, пока), но по смыслу привязка коммитов могла бы быть просто за счёт того, как git отслеживает изменения. Тут получается, что у нас проблема в том, что мы в другом репозитории живём и так легко git не поймёт, откуда какие файлы появились.

Кстати, вопрос возможной интеграции нашей версии с оригиналом (чтобы у них ссылка была на русскую версию) - это интересный вопрос. Я думаю, что надо этот вопрос поднять; постараюсь заняться этим. Если нет возражений со стороны со-авторов (в первую очередь, господина @kgv :)

**Comment by kgv** [comment]
> Кстати, вопрос возможной интеграции нашей версии с оригиналом (чтобы у них ссылка была на русскую версию)

Я уточнял это у стива (@steveklabnik), правда достаточно давно, он сказал, что планируется интеграция с другими языками, но после устаканивания самой документации. Времени прошло много с того момента и документация сильно модифицировалась, поэтому можно задать этот вопрос снова.

**Comment by steveklabnik** [comment]
Thank goodness for google translate :)

I still have a lot of work to do, but it should be significantly easier than before. So, as long as you're okay with maybe a lot of work, it might be an okay time to start translating.

**Comment by mkpankov** [comment]
@steveklabnik Thanks for the heads-up, Steve! :+1: 

Actually, there's a question we'd like to discuss with you and this happens to be proper issue to do it :)

We were discussing the proper strategy of tracking changes to docs so that we could detect and re-translate parts of book if it changes. We didn't come up with anything good enough yet, but the question is, will we integrate the translation back to original in some way (say, so that there's a link to Russian translation in the English book).

So, it seems it would make sense to merge our files to some files in main repository, at least, to have proper history (seems git would have easier time tracking changes then).

**Comment by kgv** [comment]
Я не силен в shell скриптах, но вот как вариант:

``` shell
for file in `git ls-tree --name-only rust/master src/doc/trpl/`;
do
file_name=`basename $file`;
origin_file_hash=`git log -1 --pretty=format:"%H" rust/master -- src/doc/trpl/$file_name`;
translate_file_hash=`cat hash/$file_name.hash`;

if [ "$origin_file_hash" != "$translate_file_hash" ]; then
    need_to_update="TRUE";
else
    need_to_update="FALSE";
fi

echo "$file_name";
echo -e "\tNEED TO UPDATE: $need_to_update";
echo -e "\torigin: $origin_file_hash";
echo -e "\ttranslate: $translate_file_hash";
done;
```

rust/master - это fetch оригинального репозитория, бранча master. В поддиректории hash/file_name.md.hash содержатся хеши последнего переведенного коммита из оригинала. Если он не совпадает с последним коммитом оригинала - требуется обновление.

**Comment by kgv** [comment]
@mkpankov, а вы ещё и на [корейском](https://github.com/rust-lang/rust/issues/25566#issuecomment-103087294) могёте? Или Стив просто перепутал? XD

**Comment by steveklabnik** [comment]
@mkpankov I think ultimately, that's not quite clear. Something being in the official repo means that we're responsible for its quality and keeping it going, it makes it a pseudo-official project. And while I'm comfortable with that in the long term, I'm not sure we're ready _yet_.

**Comment by mkpankov** [comment]
Пока сохранил тупо хэши, в конечном счёте я думаю надо включить rust-lang/rust в наш репозиторий подмодулем и все связи будут зафиксированы.

**Comment by mkpankov** [comment]
[Тема для обсуждения интеграции переводов в официальную книгу](https://internals.rust-lang.org/t/better-support-translations-for-the-book/3003)
