### ISSUE TITLE
В гитхабе и в гитбуке по разному интерпретируются ```

### ISSUE THREAD

**Issue by ctrlok** [kgv/rust_book_ru#88]
Привет, отличная работа. 
Хочу обратить внимание, что в гитбуке http://kgv.gitbooks.io/rust_book_ru/content/testing.html под разделом "Тестирование в документации" криво отображен код, в то время как в github маркдауне все ок. Стоит ли исправлять? Спасибо.

**Comment by mkpankov** [comment]
Спасибо!

> Хочу обратить внимание, что в гитбуке http://kgv.gitbooks.io/rust_book_ru/content/testing.html под разделом "Тестирование в документации" криво отображен код, в то время как в github маркдауне все ок. Стоит ли исправлять?

Проверяю, в rustbook похоже этот раздел тоже сломан: http://kgv.github.io/rust_book_ru/documentation.html.

А как это можно исправить?

**Comment by funkill** [comment]
rustdoc с аргументом `--markdown-playground-url` вставляет блок rusttest с текстом программы. На основном сайте эти блоки скрыты.
Можно взять стили с основного сайта.

**Comment by funkill** [comment]
Вот только с gitbook'ом это проблемы не решит, ибо он сам компилирует html

**Comment by mkpankov** [comment]
Надо попробовать на Travis накрутить компиляцию Rustbook тогда, чтобы вручную не обновлять.

**Comment by mkpankov** [comment]
А Rustbook можно собирать в PDF? Может как-то pandoc прикрутить получится? Чтобы избавиться от gitbook, который не всё понимает правильно.
