### ISSUE TITLE
Буква `ё`

### ISSUE THREAD

**Issue by funkill** [kgv/rust_book_ru#9]
Доброго времени суток.
В некоторых главах (hello-cargo, generics и static-and-dynamic-dispatch) заметил использование буквы `ё`, ранее не использовавшейся в тексте.
Отсюда вопрос: будет ли она использоваться во всём тексте (исправлять `е` на `ё`) или же только в тех случаях, когда использование `е` вместо `ё` может привести к разночтениям?
Сам я сторонник использования этой буквы везде.

**Comment by ithamsteri** [comment]
Мне `ё` тоже нравится и я пытаюсь ее вставить где можно.

**Comment by kgv** [comment]
Я не использовал букву `ё` (каюсь), но думаю будет лучше использовать `ё` везде, где этого требуют правила русского языка, а не только в ситуациях, где это может привести к разночтению.

**Comment by funkill** [comment]
Замечательно! В процессе чтения/исправления буду заменять.
