### ISSUE TITLE
Много файлов в корне - долго мотать до README

### ISSUE THREAD

**Issue by mkpankov** [kgv/rust_book_ru#92]
Предлагаю файлы переложить в подпапку а README оставить на верхнем уровне, чтобы информация для читателей была лучше видна.

**Comment by Rastopyr** [comment]
:+1: 

А gitbook не будет ругаться, или нужно ручками переписывать все ссылки?

**Comment by funkill** [comment]
Про gitbook ничего не могу сказать. Для rustbook'а надо чтоб README.md и SUMMARY.md были в одной директории, а дальше он идёт по путям из SUMMARY, так что ссылки надо будет поменять.

**Comment by kgv** [comment]
> А gitbook не будет ругаться, или нужно ручками переписывать все ссылки?

Не будет, вот у китайцев можно посмотреть: [здесь](https://github.com/linuxaged/rust_book_zh) и [здесь](https://github.com/KaiserY/rust-book-chinese). Но в SUMMARY нужно будет поменять ссылки, как написал @funkill.

Хотя я не вижу в этом такой уж необходимости... Но если  вы считаете, что так лучше - я не против.
