### ISSUE TITLE
Reviewable.io

### ISSUE THREAD

**Issue by mkpankov** [kgv/rust_book_ru#95]
В Gitter @suhr посоветовал:

> https://reviewable.io/ возможно, будет полезно для ревью перевода? Гитхаб не очень удобен в этом плане

Посмотрел - подключается вроде достаточно просто, выглядит неплохо. Ревью многих коммитов на GitHub неудобно тем, что нужно самому следить, поменял ли человек места с комментариями. Тут, я так понял, это проблема решена.

Попробуем?

**Comment by kgv** [comment]
@mkpankov попробуем. подключил
