### ISSUE TITLE
Хеш коммита в сгенерированной книге

### ISSUE THREAD

**Issue by funkill** [kgv/rust_book_ru#96]
Думаю было бы не плохо где-то в сгенерированной книге указывать версию коммита с которого она генерировалась, но пока что нет идей в какое место это лучше подставить

**Comment by jiumx60rus** [comment]
Можно на первой странице :)

**Comment by funkill** [comment]
Мне кажется, что можно сделать что-то вроде этого:
![trpl](https://cloud.githubusercontent.com/assets/4323287/7903912/3ab769a4-07f3-11e5-8392-520624b8e17a.png)

**Comment by jiumx60rus** [comment]
А можешь объяснить как происходит генерация книги(не шарю в этом)

**Comment by funkill** [comment]
Генерация происходит [rustbook'ом](https://github.com/steveklabnik/rustbook). Rustbook читает файлы README.md и SUMMARY.md.
README.md превращается в ведение (в нашем случае - некоторое предисловие к книге), SUMMARY.md - в оглавление.
Дальше rustbook формирует html-оглавление для книги, которое rustdoc вставляет перед содеримым каждой главы. 
Rustdoc вызывается для кадого файла, указанного в SUMMARY.md.
Результат работы, а так же все созданные скрипты/стили, складываются в директорию _book, откуда потом происходит заливка книги на gh-pages.

**Comment by jiumx60rus** [comment]
Оу 
А я gitbook'ом для node.js собрал и плагин для него написал уже, чтобы версия была

**Comment by funkill** [comment]
Просто здесь немного модифицированный markdown. Rust позволяет использовать в комментариях markdown-разметку, из-за чего некоторые главы отображаются криво.
Раньше книга публиковалась на gitbook'е, но из-за разметки, было решено отказаться от него и выкладывать книгу на gh-pages

**Comment by jiumx60rus** [comment]
Ясно
Спасибо будем смотреть rustbook :)
А для чего additions и patch?
