### ISSUE TITLE
Travis не смог авторизоваться на github

### ISSUE THREAD

**Issue by mkpankov** [kgv/rust_book_ru#97]
> remote: Anonymous access to kgv/rust_book_ru.git denied.
> fatal: Authentication failed for 'https://@github.com/kgv/rust_book_ru.git/'

https://travis-ci.org/kgv/rust_book_ru/builds/63622182

**Comment by mkpankov** [comment]
https://travis-ci.org/kgv/rust_book_ru/builds/63662289

> test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash additions/deploy.sh

@funkill Я не понимаю, в чём смысл этой строки. Почему не надо собирать Pull Request?

**Comment by funkill** [comment]
Сама сборка происходи выше (`./additions/rustbook/rustbook build`) и происходит для всего.
Здесь говорится, что заливать в gh-pages только то, что было собрано из мастера

**Comment by mkpankov** [comment]
@funkill ну получается, что если слили PR, то обновление отрисованной версии не произойдёт. Зачем так?

**Comment by funkill** [comment]
Не, только если как-либо обновили master (в том числе и слили PR), обновление будет. Если сейчас travis запущен для PR или для ветки, отличной от master'a, только в этом случае обновления не будет.
Иначе может придти PR в котором оставлены только README.md и SUMMARY.md и результат сборки удачно отправится в gh-pages

**Comment by mkpankov** [comment]
Тогда я не понимаю, почему до сих пор не обновился rustbook на GitHub Pages, если мы слили уже несколько PR.

**Comment by funkill** [comment]
Потому что он всё ещё не может авторизоваться и залить изменения. 
Через какое-то время ещё буду тестировать на своём репозитории да разбираться с чем может быть проблема

**Comment by mkpankov** [comment]
А почему это не вызывает ошибки в скрипте и Travis рисует зелёную галку?

**Comment by funkill** [comment]
Travis рисует зелёную галку потому что сама сборка прошла успешно. Для PR это значит, что поле принятия его в мастер, он ничего не поломает при сборке, а значит его можно сливать.
Деплой происходит в блоке команд `after_success` и там он уже похоже не смотрит коды завершения программ

**Comment by mkpankov** [comment]
Нет, что-то не сходится, там нулевое время исполнения after_success - он скрипт даже не запускал, значит

**Comment by funkill** [comment]
Если ты про двеннадцатую сборку (ссылка во втором комментарии, https://travis-ci.org/kgv/rust_book_ru/builds/63662289), то это PR и для него after_success не выполнялся. after_success выполнялся в 13 сборке (https://travis-ci.org/kgv/rust_book_ru/builds/63662679), когда PR был залит в мастер

**Comment by mkpankov** [comment]
Понятно. Странно, что код возврата не проверяется, действительно.

**Comment by funkill** [comment]
Вроде как заработало. 
19 сборка - https://travis-ci.org/kgv/rust_book_ru/builds/63721509 
В 19 сборке нечего коммитить, потому что все изменения был сделаны в 102 PR - https://travis-ci.org/kgv/rust_book_ru/builds/63720396 (чтоб не засорять мастер лишними коммитами, его не сливал с мастером и из-за этого деплой был сделан прямо из сборки PR).
В данный момент в .travis.yml установлен мой токен.
Вывод всего от git push перенаправляется в /dev/null так как в ошибках токен показывается расшифрованным.

**Comment by mkpankov** [comment]
@funkill круто! Наконец-то на Rustbook нормальные шрифты стали.

Закрываем?
